# Config file for automatic testing at travis-ci.org

language: python

install:
  - pip install tox

script:
  - tox

env:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=style
    - TOXENV=docs
    - TOXENV=coverage
